### ISSUE TITLE
Fix pushback

### ISSUE THREAD

**Issue by tailhook** [popravich/minihttp#11]
This issue tracks problem described here:
https://github.com/popravich/minihttp/commit/f849057ac0bee661e1d64374334850acc6bf640a#commitcomment-19486411

**Comment by popravich** [comment]
see @3ea08748b8156e2fe05313e3b8d13add3ffe5132

**Comment by tailhook** [comment]
No, we don't need to buffer data in. The whole point of backpressure is not to read data in.

Solution would be to try read after polling if we haven't done reading before.

**Comment by tailhook** [comment]
Furthermore, it doesn't fix the problem :) I.e. the data is in the input buffer, but nobody would trigger the future to actually parse request from there.

**Comment by tailhook** [comment]
It's not an issue any more since `tk-bufstream` is used. The real issue is #5
